name: Release
on: workflow_dispatch

permissions: write-all

env:
  PROJECT_NAME: ModsEngine

jobs:
  build:
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: Windows x64
            os: windows-2022
            buildArgs: "windows -final -X64 -D HXCPP_X64 -D 64bits"
            artifactName: Windows-x64
            artifactPath: export/release/windows/bin/*
          - name: Windows x32
            os: windows-2022
            buildArgs: "windows -final -X32 -D HXCPP_X32 -D 32bits"
            artifactName: Windows-x32
            artifactPath: export/release/windows/bin/*
          - name: Linux
            os: ubuntu-22.04
            buildArgs: "linux -final"
            artifactName: Linux
            artifactPath: export/release/linux/bin/*
          - name: MacOS
            os: macos-15
            buildArgs: "mac -final"
            artifactName: MacOS
            artifactPath: export/release/macos/bin/*
          - name: Android
            os: macos-15
            buildArgs: "android -final -D officialBuild"
            artifactName: Android
            artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"
          - name: Android-x86-64
            os: macos-15
            buildArgs: "android -final -DXCPP_X86_64 -D officialBuild"
            artifactName: Android-x86-64
            artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"
          - name: Android-ARM-64
            os: macos-15
            buildArgs: "android -final -DXCPP_ARM64 -D officialBuild"
            artifactName: Android-ARM-64
            artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"
          - name: iOS
            os: macos-15
            buildArgs: "ios -final -nosign"
            artifactName: iOS
            artifactPath: "export/release/ios/build/Release-iphoneos/*.ipa"
    uses: ./.github/workflows/build.yml
    with:
        name: ${{ matrix.name }}
        os: ${{ matrix.os }}
        buildArgs: ${{ matrix.buildArgs }}
        artifactName: ${{ matrix.artifactName }}
        artifactPath: ${{ matrix.artifactPath }}

  Releaser:
    needs: [build]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Download Windows x64 Build
        uses: actions/download-artifact@main
        with:
          name: Windows-x64
          path: /home/runner/Windows-x64

      - name: Zip Windows x64 Build For Release
        run: |
          cd /home/runner/Windows-x64
          zip -r "/home/runner/${{ env.PROJECT_NAME }}-Windows-x64.zip" "Windows-x64-release.zip" .

      - name: Download Windows x32 Build
        uses: actions/download-artifact@main
        with:
          name: Windows-x32
          path: /home/runner/Windows-x32

      - name: Zip Windows x32 Build For Release
        run: |
          cd /home/runner/Windows-x32
          zip -r "/home/runner/${{ env.PROJECT_NAME }}-Windows-x32.zip" "Windows-x32-release.zip" .

      - name: Download Linux Build
        uses: actions/download-artifact@main
        with:
          name: Linux
          path: /home/runner/Linux

      - name: Zip Linux Build For Release
        run: |
          cd /home/runner/Linux
          zip -r "/home/runner/${{ env.PROJECT_NAME }}-Linux.zip" "Linux-release.zip" .

      - name: Download MacOS Build
        uses: actions/download-artifact@main
        with:
          name: MacOS
          path: /home/runner/MacOS

      - name: Zip MacOS Build For Release
        run: |
          cd /home/runner/MacOS
          zip -r "/home/runner/${{ env.PROJECT_NAME }}-MacOS.zip" "MacOS-release.zip" .

      - name: Download Android Build
        uses: actions/download-artifact@main
        with:
          name: Android
          path: /home/runner

      - name: Move Android File
        run: mv /home/runner/${{ env.PROJECT_NAME }}-release.apk /home/runner/${{ env.PROJECT_NAME }}-Android-release.apk

      - name: Download Android Build
        uses: actions/download-artifact@main
        with:
          name: Android-ARM-64
          path: /home/runner

      - name: Move Android File
        run: mv /home/runner/${{ env.PROJECT_NAME }}-release.apk /home/runner/${{ env.PROJECT_NAME }}-Android-ARM64-release.apk

      - name: Download Android Build
        uses: actions/download-artifact@main
        with:
          name: Android-x86-64
          path: /home/runner

      - name: Move Android File
        run: mv /home/runner/${{ env.PROJECT_NAME }}-release.apk /home/runner/${{ env.PROJECT_NAME }}-Android-x86-64-release.apk

      - name: Download iOS Build
        uses: actions/download-artifact@main
        with:
          name: iOS
          path: ${{ github.workspace }}

      - name: Move iOS File
        run: mv ${{ github.workspace }}/${{ env.PROJECT_NAME }}.ipa /home/runner/${{ env.PROJECT_NAME }}-iOS-release.ipa

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4

      - name: Publish The Release
        uses: softprops/action-gh-release@v2
        with:
          name: "6.9.9"
          tag_name: "6.9.9"
          last_release: false
          files: |
            /home/runner/*.apk
            /home/runner/*.ipa
            /home/runner/*.zip
